version: "3.2"

services:
  blob:
    image: microsoft/azure-storage-emulator
    ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"
  db:
    image: piranha-sql-server
    build:
      context: .
      dockerfile: sql-dev/Dockerfile
    ports:
      - "1402:1433"
    environment:
      SA_PASSWORD: "DevDatabase123"
      ACCEPT_EULA: "Y"