version: "3.2"

services:
  blob:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
        - "10000:10000"
  db:
    image: piranha-sql-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "1402:1433"
    environment:
      SA_PASSWORD: "DevDatabase123"
      ACCEPT_EULA: "Y"